project:
  type: website
  execute-dir: project
  output-dir: docs

website:
  title: "Function of the week for BSTA526 Winter 24"
  navbar:
    background: primary
    search: true
    logo: "images/IMG_6759_med.png"
    foreground: "#fff"
    collapse-below: sm
    right:
      - href: index.qmd
        text: Home
      - href: presentations.qmd
        text: Presentations

  sidebar:
    style: "docked"
    search: true
    collapse-level: 4
    contents:
      - href: index.qmd
        text: Home
      - href: function_of_the_week_McMonigal.qmd
        text: dplyr::n_distinct  
      - href: function_of_the_week_ECHALUSE.qmd
        text: lubridate::ceiling_date()
      

            
format:
  html:
    theme: minty
    css: styles.css
    toc: true

