project:
  type: website
  execute-dir: project
  output-dir: docs

website:
  title: "Functions of the week for BSTA526 Winter 2024"
  navbar:
    background: primary
    search: true
    logo: "images/IMG_6759_med.png"
    foreground: "#fff"
    collapse-below: sm
    right:
      - href: index.qmd
        text: Home


  sidebar:
    style: "docked"
    search: true
    collapse-level: 4
    contents:
      - href: index.qmd
        text: Home

      - href: function_of_the_week_McMonigal.qmd
        text: dplyr::n_distinct  
      - href: function_of_the_week_KELLY.qmd
        text: dplyr::near()  
      - href: function_of_the_week_CIRELL_ALFONSO.qmd
        text: dplyr::slice_sample  
      - href: function_of_the_week_Higbee.qmd
        text: forcats::fct_shift  
      - href: function_of_the_week_bsta356_Cornacchione.qmd
        text: ggplot2::geom_map()  
      - href: function_of_the_week_Chapela.qmd
        text: janitor::get_dupes
      - href: function_of_the_week_ECHALUSE.qmd
        text: lubridate::ceiling_date()
      - href: function_of_the_week_Clem_write.xlsx.qmd
        text: openxlsx::write.xlsx()
      - href: function_of_the_week_Delsey_str_match_presentation.qmd
        text: stringr::str-match       
      - href: function_of_the_week_Cristancho.qmd
        text: tidyr::uncount()  

   


         
format:
  html:
    theme: minty
    css: styles.css
    toc: true

